/**
 * export-abi.ts
 *
 * Reads the compiled Foundry artifact for `EventTicketing` and regenerates
 * `src/abi.ts`, embedding the ABI array as a strongly-typed `const`.
 *
 * Run from the package root:
 *   pnpm --filter @nftickets/shared run export-abi
 *
 * The Foundry build must have produced the artifact first:
 *   pnpm --filter @nftickets/contracts run build   (i.e. `forge build`)
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const packageRoot = resolve(__dirname, "..");

// Location of the Foundry artifact relative to this package.
const artifactPath = resolve(
  packageRoot,
  "../contracts/out/EventTicketing.sol/EventTicketing.json",
);
const outputPath = resolve(packageRoot, "src/abi.ts");

function main(): void {
  let raw: string;
  try {
    raw = readFileSync(artifactPath, "utf8");
  } catch {
    throw new Error(
      `Could not read Foundry artifact at ${artifactPath}. ` +
        `Build the contracts first with \`pnpm --filter @nftickets/contracts run build\`.`,
    );
  }

  const artifact = JSON.parse(raw) as { abi?: unknown };
  if (!Array.isArray(artifact.abi)) {
    throw new Error(
      `Artifact at ${artifactPath} does not contain an \`abi\` array.`,
    );
  }

  const header = `// AUTO-GENERATED by scripts/export-abi.ts — DO NOT EDIT BY HAND.
//
// Source: packages/contracts/out/EventTicketing.sol/EventTicketing.json
// Regenerate: pnpm --filter @nftickets/shared run export-abi
`;

  const body = `export const eventTicketingAbi = ${JSON.stringify(
    artifact.abi,
    null,
    2,
  )} as const;\n`;

  writeFileSync(outputPath, `${header}\n${body}`);
  // eslint-disable-next-line no-console
  console.log(
    `[export-abi] Wrote ${artifact.abi.length} ABI entries to ${outputPath}`,
  );
}

main();
